---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vllm-omni-qwen-image-2512
  labels:
    example.com/vllm-omni: "true"
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/nickcao/comfyui-vllm-omni/vllm-omni-mock:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MODEL
              value: "Qwen/Qwen-Image-2512"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vllm-omni-z-image-turbo
  labels:
    example.com/vllm-omni: "true"
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/nickcao/comfyui-vllm-omni/vllm-omni-mock:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MODEL
              value: "Tongyi-MAI/Z-Image-Turbo"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comfyui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: comfyui
subjects:
  - kind: ServiceAccount
    name: comfyui
    namespace: default
roleRef:
  kind: ClusterRole
  name: knative-serving-namespaced-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: comfyui
spec:
  template:
    spec:
      serviceAccountName: comfyui
      containers:
        - image: ghcr.io/nickcao/comfyui-vllm-omni/comfyui:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8188
